### PR TITLE
Feature/update express

### PR DESCRIPTION
**Pull request by kirrg001**
#### contains
- add new dependencies because of express migration
- res.router isnt needed anymore (express 4 has now a strict order pattern instead)
- res.send is deprecated (we use res.json instead)
- no default favicon anymore
- http delete instead of http del function

#### tests
make test-all is green

#### questions
there are no http tests (or are there?), i simply run an example server and did ***some*** http calls.
shall i create some basic http tests to ensure basic usage?but notice: i dont speak coffee-script ;)

### CODE REVIEW

**Comment by behrad** [comment]
this is great @kirrg001 
you can find a simple HTTP API test for bulk job create that will be merge in... the same module can be used if you are OK with it https://github.com/LearnBoost/kue/pull/527

**Comment by kirrg001** [comment]
yes i can put more basic http tests into this module from #527 
the only thing which is strange are the 8 spaces. 
if you don't mind i would like to change it to 2 or if you wish to 4 spaces in my PR.

**Comment by behrad** [comment]
use 2, or 4! we have some inconsistencies in style, we should fix this around Kue's code

**Comment by kirrg001** [comment]
cool will use 2 indents :+1: 

can you merge #527 please?(if its okay from your side)
then i will start with tests tomorrow and finish the PR.

thanks!

**Comment by EgoAleSum** [comment]
Sorry for the 8 spaces. I normally indent with tabs, and my editor is set to that (hence the tabs in most places). I based that PR on someone else's code, which was indented with 4 spaces, and that's why the mixed style. Feel free to change it :)

**Comment by kirrg001** [comment]
happens :+1:

**Comment by behrad** [comment]
#527 merged

**Comment by kirrg001** [comment]
thanks!
keep in touch

**Comment by kirrg001** [comment]
Whoops why merged?Wirkung on tests right now.

**Comment by behrad** [comment]
:)) no problem, my mistake not too double check when saw your commits...
We can revert or wait to commit an update when you finished

**Comment by kirrg001** [comment]
Update is fine :) thanks

**Comment by behrad** [comment]
thank you @kirrg001

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/commit/55c624478bff5c114db594b3014c9fc828c34eb6

**Comment by kirrg001** [comment]
thanks!

**Comment by EgoAleSum** [comment]
It gives me a Jade error now

`````
Error: /Users/Alessandro/Desktop/dev/server/node_modules/kue/lib/http/views/_filter.jade:4
   2|   option(value='') filter by
   3|   - each type in types
 > 4|   option(value=type)= type

expected "indent", but got "newline"
   at Parser.expect (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:163:13)
   at Parser.block (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:655:10)
   at Parser.parseEach (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:394:23)
   at Parser.parseExpr (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:225:21)
   at Parser.block (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:660:25)
   at Parser.tag (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:777:26)
   at Parser.parseTag (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:690:17)
   at Parser.parseExpr (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:199:21)
   at Parser.parse (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:131:25)
   at Parser.parseInclude (/Users/Alessandro/Desktop/dev/server/node_modules/kue/node_modules/jade/lib/parser.js:529:22)
````

**Comment by behrad** [comment]
embarrassing! that is my fault, running code formater against kue directory, all jade files are corrupted, fixing this, will commit soon

**Comment by EgoAleSum** [comment]
Thanks!

**Pull request merged**
