### PR TITLE
Upgrade Redis. Fixes https://github.com/LearnBoost/kue/issues/511.

### PR DESCRIPTION
**Pull request by bradvogel**

### CODE REVIEW

**Comment by bradvogel** [comment]
@behrad

**Comment by wearhere** [comment]
:+1:

**Comment by bradvogel** [comment]
Thanks @behrad . When are you planning to bump the npm module?

**Comment by behrad** [comment]
I prefer `npm install kue` to install latest stables, I have not tested this yes :( But I'll do it in a week or two

**Pull request merged**
